---
title: "README"
author: "Glabenweek"
date: "September 23, 2015"
output: html_document
---

# Getting and Cleaning Data course - COURSE PROJECT



 

# Background

 One of the most exciting areas in all of data science right now is wearable computing.
 Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms
 to attract new users. The data linked to from the course website represent data collected
 from the accelerometers from the Samsung Galaxy S smartphone.
 
Aim of this script:
 
1 Merges the training and the test sets to create one data set.

2 Extracts only the measurements on the mean and standard deviation for each measurement. 

3 Uses descriptive activity names to name the activities in the data set.

4 Appropriately labels the data set with descriptive variable names. 

5 From the data set in step 4, creates a second, independent tidy data set with the average of each variable
  for each activity and each subject.

###############################################################################

# Content

- *run_analysis.R* - This file contains the script,
- *Code book.txt* - This file contains the description of the variables generated by the script.

# Library required 

dplyr (automatically installed by the script)


# Description and output

The *run_analysis.R* will download the zip file required for the project, unzip the files in an automatically created "data project' folder, carry out the 5 steps described previously, and generate a *Tidy.Data.txt" file in the working directory (space separator).

